# Generated by Django 4.2.29 on 2026-03-11 08:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('domain_url', models.URLField(blank=True, max_length=500, null=True)),
                ('platform', models.CharField(choices=[('WORDPRESS', 'WordPress'), ('SHOPIFY', 'Shopify'), ('CUSTOM', 'Custom')], default='WORDPRESS', max_length=50)),
                ('webhook_secret', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
