# Generated by Django 4.2.29 on 2026-03-14 18:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('max_clients', models.IntegerField(default=1)),
                ('max_sessions_per_month', models.IntegerField(default=500)),
                ('price_monthly', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='chatbot_color',
            field=models.CharField(default='#3B82F6', max_length=20),
        ),
        migrations.AddField(
            model_name='client',
            name='chatbot_logo_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='chatbot_name',
            field=models.CharField(default='AI Assistant', max_length=100),
        ),
        migrations.AddField(
            model_name='client',
            name='cta_message',
            field=models.CharField(default="You're clearly ready — grab your exclusive discount:", max_length=255),
        ),
        migrations.AddField(
            model_name='client',
            name='discount_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='fomo_countdown_seconds',
            field=models.IntegerField(default=600),
        ),
        migrations.AddField(
            model_name='client',
            name='fomo_offer_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='ingestion_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('DONE', 'Done'), ('FAILED', 'Failed')], default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='client',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='client',
            name='total_pages_ingested',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='client',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('superadmin', 'Super Admin'), ('tenant_admin', 'Tenant Admin'), ('end_user', 'End User')], default='tenant_admin', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TenantProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=255)),
                ('sessions_this_month', models.IntegerField(default=0)),
                ('clients', models.ManyToManyField(blank=True, to='users.client')),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.plan')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
