# Generated by Django 4.2.29 on 2026-03-13 06:55
# Fixed: removed duplicate AddField operations already applied by
# 0002_plan_client_chatbot_color_... which runs first alphabetically.
# Duplicate operations are preserved as state-only via SeparateDatabaseAndState
# so Django's migration state graph remains accurate.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        # RemoveField is unique to this branch — run it against the DB.
        migrations.RemoveField(
            model_name='client',
            name='webhook_secret',
        ),
        # Fields below were already added to the DB by 0002_plan_... (runs first
        # alphabetically: 'plan' < 'remove'). We declare them as state-only so
        # Django's migration state remains consistent, but skip the actual SQL.
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AddField(
                    model_name='client',
                    name='chatbot_color',
                    field=models.CharField(default='#3B82F6', max_length=7),
                ),
                migrations.AddField(
                    model_name='client',
                    name='chatbot_logo_url',
                    field=models.URLField(blank=True, max_length=1000, null=True),
                ),
                migrations.AddField(
                    model_name='client',
                    name='chatbot_name',
                    field=models.CharField(default='AI Assistant', max_length=100),
                ),
                migrations.AddField(
                    model_name='client',
                    name='ingestion_status',
                    field=models.CharField(
                        choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'),
                                 ('DONE', 'Done'), ('FAILED', 'Failed')],
                        default='PENDING', max_length=20,
                    ),
                ),
                migrations.AddField(
                    model_name='client',
                    name='is_active',
                    field=models.BooleanField(default=True),
                ),
                migrations.AddField(
                    model_name='client',
                    name='total_pages_ingested',
                    field=models.IntegerField(default=0),
                ),
            ],
        ),
        # plan CharField is unique to this branch (removed again in 0003).
        migrations.AddField(
            model_name='client',
            name='plan',
            field=models.CharField(
                choices=[('FREE', 'Free'), ('PRO', 'Pro'), ('ENTERPRISE', 'Enterprise')],
                default='FREE', max_length=50,
            ),
        ),
    ]
