# Generated by Django 4.2.29 on 2026-03-13 10:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0002_remove_client_webhook_secret_client_chatbot_color_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('max_clients', models.IntegerField(default=1)),
                ('max_sessions_per_month', models.IntegerField(default=500)),
                ('price_monthly', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
            ],
        ),
        migrations.RemoveField(
            model_name='client',
            name='plan',
        ),
        migrations.AddField(
            model_name='client',
            name='cta_message',
            field=models.CharField(blank=True, default="You're clearly ready — grab your exclusive discount:", max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='discount_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='fomo_countdown_seconds',
            field=models.IntegerField(default=600),
        ),
        migrations.AddField(
            model_name='client',
            name='fomo_offer_text',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('superadmin', 'Super Admin'), ('tenant_admin', 'Tenant Admin'), ('end_user', 'End User')], default='tenant_admin', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TenantProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sessions_this_month', models.IntegerField(default=0)),
                ('company_name', models.CharField(blank=True, max_length=255)),
                ('clients', models.ManyToManyField(blank=True, related_name='tenant_owners', to='users.client')),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.plan')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
