# Generated by Django 4.2.29 on 2026-03-17 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_plan_remove_client_plan_client_cta_message_and_more'),
        ('users', '0003_planhistory'),
    ]

    operations = [
    ]
