# Generated by Django 4.2.29 on 2026-03-17 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_merge_20260317_0404'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='webhook_secret',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='chatbot_color',
            field=models.CharField(default='#3B82F6', max_length=20),
        ),
        migrations.AlterField(
            model_name='client',
            name='chatbot_logo_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='cta_message',
            field=models.CharField(default="You're clearly ready — grab your exclusive discount:", max_length=255),
        ),
        migrations.AlterField(
            model_name='client',
            name='fomo_offer_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tenantprofile',
            name='clients',
            field=models.ManyToManyField(blank=True, to='users.client'),
        ),
    ]
