# Generated by Django 4.2.29 on 2026-03-25 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_add_analyticevent_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='notification_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
