# Generated by Django 4.2.29 on 2026-05-04 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_v2_scaffold_tenant_affiliate_marketing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('PLAN_CHANGE', 'Plan Changed'), ('IMPERSONATE_START', 'Impersonation Started'), ('IMPERSONATE_END', 'Impersonation Ended'), ('CLIENT_CREATE', 'Client Created'), ('CLIENT_DELETE', 'Client Deleted'), ('FEATURE_OVERRIDE', 'Feature Override Granted'), ('FEATURE_OVERRIDE_REVOKE', 'Feature Override Revoked'), ('TRIAL_EXTEND', 'Trial Extended'), ('ACCOUNT_SUSPEND', 'Account Suspended'), ('ACCOUNT_REACTIVATE', 'Account Reactivated'), ('SCRAPE_TRIGGER', 'Scrape Triggered'), ('PASSWORD_RESET', 'Password Reset'), ('BILLING_CHANGE', 'Billing Changed'), ('BROADCAST_SEND', 'Broadcast Email Sent')], max_length=50),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='platformannouncement',
            name='announcement_type',
            field=models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('feature', 'New Feature'), ('maintenance', 'Maintenance')], default='info', max_length=20),
        ),
        migrations.AlterField(
            model_name='platformannouncement',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='platformannouncement',
            name='target',
            field=models.CharField(choices=[('all', 'All Tenants'), ('free', 'Free Plan'), ('paid', 'Paid Plans'), ('specific', 'Specific Tenant')], default='all', max_length=20),
        ),
        migrations.AlterField(
            model_name='tenantfeatureoverride',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
