# Generated by Django 4.2.29 on 2026-05-22 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_fix_placeholder_chatbot_names'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='return_policy_blurb',
            field=models.CharField(blank=True, default='', help_text='Short pre-purchase return policy answer (e.g. "30-day no-questions returns. Free return shipping.")', max_length=300),
        ),
        migrations.AddField(
            model_name='client',
            name='shipping_blurb',
            field=models.CharField(blank=True, default='', help_text='Short pre-purchase shipping answer (e.g. "We ship nationwide in 3-5 business days. Exact rates depend on your area.")', max_length=300),
        ),
    ]
