# Generated by Django 4.2.29 on 2026-05-22 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_add_faq_blurbs'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='addon_price_per_image',
            field=models.DecimalField(decimal_places=4, default=0.05, max_digits=6),
        ),
        migrations.AddField(
            model_name='plan',
            name='addon_price_per_message',
            field=models.DecimalField(decimal_places=4, default=0.005, max_digits=6),
        ),
        migrations.AddField(
            model_name='plan',
            name='addon_price_per_video',
            field=models.DecimalField(decimal_places=4, default=0.25, max_digits=6),
        ),
        migrations.AddField(
            model_name='plan',
            name='addon_price_per_voice',
            field=models.DecimalField(decimal_places=4, default=0.1, max_digits=6),
        ),
        migrations.AddField(
            model_name='plan',
            name='max_videos_per_month',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tenantprofile',
            name='addon_videos',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tenantprofile',
            name='videos_this_month',
            field=models.IntegerField(default=0),
        ),
    ]
