# Generated by Django 4.2.29 on 2026-05-22 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_add_videos_and_addon_prices'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddOnPurchase',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('message', 'Messages'), ('image', 'Images'), ('voice', 'Voice commands'), ('video', 'Videos')], max_length=10)),
                ('quantity', models.IntegerField()),
                ('unit_price_usd', models.DecimalField(decimal_places=4, max_digits=8)),
                ('total_paid_usd', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=12)),
                ('stripe_checkout_session_id', models.CharField(blank=True, max_length=200)),
                ('stripe_payment_intent_id', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addon_purchases', to='users.tenantprofile')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant', '-created_at'], name='users_addon_tenant__dc80cb_idx'), models.Index(fields=['status', '-created_at'], name='users_addon_status_fa2466_idx')],
            },
        ),
    ]
