# Generated by Django 4.2.29 on 2026-05-22 11:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0017_v2_architecture_stubs'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0022_addon_purchase_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketingCampaign',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('channel', models.CharField(choices=[('email', 'Email'), ('whatsapp', 'WhatsApp'), ('sms', 'SMS')], default='email', max_length=10)),
                ('subject', models.CharField(blank=True, max_length=255)),
                ('body', models.TextField(blank=True)),
                ('target_filter_json', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('sending', 'Sending'), ('sent', 'Sent'), ('canceled', 'Canceled')], default='draft', max_length=10)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marketing_campaigns', to='users.client')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AffiliateProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referral_code', models.CharField(max_length=32, unique=True)),
                ('commission_rate', models.DecimalField(decimal_places=4, default=0.2, max_digits=5)),
                ('payout_email', models.EmailField(blank=True, max_length=254)),
                ('is_active', models.BooleanField(default=True)),
                ('total_earned_usd', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='affiliate_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AffiliateConversion',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('plan_price_at_event_usd', models.DecimalField(decimal_places=2, max_digits=8)),
                ('commission_usd', models.DecimalField(decimal_places=2, max_digits=8)),
                ('status', models.CharField(choices=[('pending', 'Pending qualification period'), ('ready', 'Ready to pay out'), ('paid', 'Paid'), ('reversed', 'Reversed (refund/chargeback)')], default='pending', max_length=10)),
                ('stripe_subscription_id', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('qualified_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('affiliate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conversions', to='users.affiliateprofile')),
                ('plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='users.plan')),
                ('referred_tenant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='users.tenantprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MarketingDelivery',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('recipient_email', models.EmailField(blank=True, max_length=254)),
                ('recipient_phone', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('sent', 'Sent'), ('delivered', 'Delivered (provider confirmed)'), ('opened', 'Opened (email pixel / link click)'), ('clicked', 'CTA clicked'), ('bounced', 'Bounced'), ('unsubscribed', 'Unsubscribed'), ('failed', 'Failed')], default='queued', max_length=14)),
                ('provider_message_id', models.CharField(blank=True, max_length=200)),
                ('error_message', models.TextField(blank=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('clicked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='users.marketingcampaign')),
                ('visitor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='chat.visitor')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['campaign', 'status'], name='users_marke_campaig_4c434f_idx'), models.Index(fields=['recipient_email'], name='users_marke_recipie_1f24a5_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='marketingcampaign',
            index=models.Index(fields=['client', '-created_at'], name='users_marke_client__f70b7b_idx'),
        ),
        migrations.AddIndex(
            model_name='marketingcampaign',
            index=models.Index(fields=['status', 'scheduled_at'], name='users_marke_status_5c1334_idx'),
        ),
        migrations.AddIndex(
            model_name='affiliateprofile',
            index=models.Index(fields=['referral_code'], name='users_affil_referra_b7c2a5_idx'),
        ),
        migrations.AddIndex(
            model_name='affiliateconversion',
            index=models.Index(fields=['affiliate', '-created_at'], name='users_affil_affilia_9587a9_idx'),
        ),
        migrations.AddIndex(
            model_name='affiliateconversion',
            index=models.Index(fields=['status', '-created_at'], name='users_affil_status_fbdd87_idx'),
        ),
    ]
