# Generated by Django 4.2.29 on 2026-05-22 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_v2_architecture_stubs'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='scarcity_blurb',
            field=models.CharField(blank=True, default='', help_text='Optional urgency line for late-stage hesitation, e.g. "Our top sellers can go fast — want me to check availability?" or "This sale ends Friday at midnight." Leave blank to disable scarcity prompts.', max_length=300),
        ),
    ]
