# Generated by Django 4.2.29 on 2026-05-24 23:31

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_scarcity_blurb'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('invoice_number', models.CharField(max_length=32, unique=True)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('plan_name_at_issue', models.CharField(blank=True, max_length=100)),
                ('company_name_at_issue', models.CharField(blank=True, max_length=255)),
                ('recipient_email_at_issue', models.EmailField(blank=True, max_length=254)),
                ('subtotal_usd', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('tax_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('tax_usd', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_usd', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('line_items', models.JSONField(default=list)),
                ('usage_summary', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('issued', 'Issued'), ('sent', 'Sent (emailed)'), ('paid', 'Paid'), ('void', 'Void')], default='draft', max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='users.tenantprofile')),
            ],
            options={
                'ordering': ['-period_start', '-created_at'],
                'indexes': [models.Index(fields=['tenant', '-period_start'], name='users_invoi_tenant__bb9303_idx'), models.Index(fields=['status', '-created_at'], name='users_invoi_status_3ffbb7_idx')],
                'unique_together': {('tenant', 'period_start')},
            },
        ),
    ]
