# Generated by Django 4.2.29 on 2026-06-10 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_invoice_branding_snapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantprofile',
            name='manual_plan_override',
            field=models.BooleanField(default=False),
        ),
    ]
