# Generated by Django 4.2.29 on 2026-06-23 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_tenantprofile_manual_plan_override'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='shopify_access_token',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='client',
            name='shopify_connected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='shopify_scopes',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='client',
            name='shopify_shop_domain',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
