# Generated by Django 4.2.29 on 2026-06-24 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_client_shopify_access_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='instagram_access_token',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='instagram_business_account_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='instagram_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='client',
            name='instagram_verify_token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='allow_instagram',
            field=models.BooleanField(default=False),
        ),
    ]
