# Generated by Django 4.2.29 on 2026-06-25 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_client_instagram_access_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='assistant_intro',
            field=models.CharField(default="Hi! I'm your AI Shopping Assistant.", max_length=200),
        ),
        migrations.AddField(
            model_name='client',
            name='auto_close_seconds',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='client',
            name='notification_timeout_seconds',
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name='client',
            name='page_rules',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='client',
            name='proactive_notifications_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
