# Generated by Django 4.2.29 on 2026-06-25 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0030_client_assistant_intro_client_auto_close_seconds_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='widget_style',
            field=models.CharField(choices=[('classic', 'Classic'), ('assistant', 'Assistant Card')], default='classic', max_length=20),
        ),
    ]
