# Generated by Django 4.2.29 on 2026-06-26 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0031_client_widget_style'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='active_offers',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
