[pytest]
DJANGO_SETTINGS_MODULE = checkfunnel.test_settings
python_files = tests/test_*.py test_*.py
python_classes = Test*
python_functions = test_*
addopts = --tb=short -q --no-header
filterwarnings =
    ignore::DeprecationWarning
    ignore::PendingDeprecationWarning
