# Generated by Django 4.2.29 on 2026-03-17 04:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0005_add_analyticevent_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, max_length=255)),
                ('event_type', models.CharField(choices=[('page_view', 'Page View'), ('pricing_visit', 'Pricing Page Visit'), ('exit_intent', 'Exit Intent'), ('scroll_depth', 'Scroll Depth'), ('session_start', 'Session Start'), ('beacon', 'Beacon')], default='beacon', max_length=50)),
                ('page_url', models.CharField(blank=True, max_length=2000, null=True)),
                ('payload', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='analytic_events', to='users.client')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['session_id', 'event_type'], name='analytics_a_session_47c6e7_idx'), models.Index(fields=['client', 'created_at'], name='analytics_a_client__5cce10_idx')],
            },
        ),
    ]
