# Generated by Django 4.2.29 on 2026-05-22 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_add_analyticevent_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analyticevent',
            name='event_type',
            field=models.CharField(choices=[('page_view', 'Page View'), ('pricing_visit', 'Pricing Page Visit'), ('exit_intent', 'Exit Intent'), ('scroll_depth', 'Scroll Depth'), ('session_start', 'Session Start'), ('beacon', 'Beacon'), ('click', 'Click'), ('cta_click', 'CTA Click'), ('add_to_cart', 'Add to Cart'), ('rage_click', 'Rage Click'), ('form_focus', 'Form Focus'), ('form_abandoned', 'Form Abandoned'), ('copy', 'Copy Event')], default='beacon', max_length=50),
        ),
    ]
