# Generated by Django 4.2.29 on 2026-03-10 05:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('session_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('visitor_id', models.CharField(db_index=True, max_length=255)),
                ('current_intent_ema', models.FloatField(default=0.0)),
                ('current_budget_ema', models.FloatField(default=0.0)),
                ('current_urgency_ema', models.FloatField(default=0.0)),
                ('previous_intent_ema', models.FloatField(default=0.0)),
                ('previous_budget_ema', models.FloatField(default=0.0)),
                ('previous_urgency_ema', models.FloatField(default=0.0)),
                ('intent_trend', models.CharField(choices=[('UP', 'Up'), ('DOWN', 'Down'), ('FLAT', 'Flat')], default='FLAT', max_length=10)),
                ('budget_trend', models.CharField(choices=[('UP', 'Up'), ('DOWN', 'Down'), ('FLAT', 'Flat')], default='FLAT', max_length=10)),
                ('urgency_trend', models.CharField(choices=[('UP', 'Up'), ('DOWN', 'Down'), ('FLAT', 'Flat')], default='FLAT', max_length=10)),
                ('conversation_state', models.CharField(choices=[('RESEARCH', 'Research Mode'), ('EVALUATION', 'Evaluation Mode'), ('OBJECTION', 'Objection Mode'), ('RECOVERY', 'Recovery Mode'), ('READY_TO_BUY', 'Ready to Buy')], default='RESEARCH', max_length=20)),
                ('message_count', models.IntegerField(default=0)),
                ('chat_history', models.JSONField(default=list)),
                ('behavioral_context', models.JSONField(default=dict)),
                ('lead_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('lead_phone', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
