# Generated by Django 4.2.29 on 2026-03-13 10:16
# Fixed: heat_score, takeover_active, taken_over_by, closing_triggered were already
# added by 0003_chatsession_closing_triggered_... (runs first alphabetically: 'c' < 's').
# This migration only adds the fields unique to this branch.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_chatsession_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='kanban_state',
            field=models.CharField(
                choices=[
                    ('NEW', 'New'),
                    ('ENGAGED', 'Engaged'),
                    ('HOT_LEAD', 'Hot Lead'),
                    ('CONVERTED', 'Converted'),
                    ('LOST', 'Lost'),
                ],
                default='NEW',
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='afk_nudge_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='last_visitor_message_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
