# Generated by Django 4.2.29 on 2026-03-13 10:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0002_chatsession_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='closing_triggered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='heat_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='last_nudge_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='nudge_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='taken_over_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='taken_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='takeover_active',
            field=models.BooleanField(default=False),
        ),
    ]
