# Generated by Django 4.2.29 on 2026-03-17 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_chatsession_closing_triggered_chatsession_heat_score_and_more'),
        ('chat', '0003_chatsession_stage2_fields'),
    ]

    operations = [
    ]
