# Generated by Django 4.2.29 on 2026-03-17 04:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0004_merge_20260317_0403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatsession',
            name='taken_over_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='takeover_sessions', to=settings.AUTH_USER_MODEL),
        ),
    ]
