# Generated by Django 4.2.29 on 2026-03-25 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_add_lead_capture_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='hot_lead_email_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='human_requested',
            field=models.BooleanField(default=False),
        ),
    ]
