# Generated by Django 4.2.29 on 2026-05-22 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0015_remove_state_instructions_prompt'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='llmcalllog',
            new_name='chat_llmcal_client__1e531a_idx',
            old_name='chat_llm_client_4f1b5c_idx',
        ),
        migrations.RenameIndex(
            model_name='llmcalllog',
            new_name='chat_llmcal_status_72dd45_idx',
            old_name='chat_llm_status_8e2d11_idx',
        ),
        migrations.RenameIndex(
            model_name='llmcalllog',
            new_name='chat_llmcal_model_c73f49_idx',
            old_name='chat_llm_model_2a9f43_idx',
        ),
        migrations.RenameIndex(
            model_name='llmcalllog',
            new_name='chat_llmcal_is_byok_d90e5f_idx',
            old_name='chat_llm_byok_7c44e9_idx',
        ),
        migrations.RenameIndex(
            model_name='visitor',
            new_name='chat_visito_client__55a215_idx',
            old_name='chat_visito_client__d51017_idx',
        ),
        migrations.AddField(
            model_name='chatsession',
            name='outcome',
            field=models.CharField(choices=[('open', 'Still in conversation'), ('converted', 'Converted'), ('captured', 'Contact captured'), ('escalated', 'Escalated to human'), ('abandoned', 'Abandoned mid-chat'), ('ghost', 'Ghost session (no messages)')], db_index=True, default='open', max_length=12),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='outcome_set_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
