# Generated by Django 4.2.29 on 2026-05-22 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0016_session_outcome'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='marketing_opt_out',
            field=models.BooleanField(default=False),
        ),
    ]
