# Generated by Django 4.2.29 on 2026-06-04 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_invoice_branding_snapshot'),
        ('chat', '0018_chatsession_conversation_summary'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductLinkClick',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('session_id', models.CharField(db_index=True, max_length=255)),
                ('url', models.URLField(max_length=2000)),
                ('link_text', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_link_clicks', to='users.client')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['client', '-created_at'], name='chat_produc_client__e74ffd_idx'), models.Index(fields=['client', 'url'], name='chat_produc_client__124d8a_idx')],
            },
        ),
    ]
