# Generated by Django 4.2.29 on 2026-06-10 03:04

from django.db import migrations, models


def backfill_last_message_at(apps, schema_editor):
    """Seed last_message_at for existing rows.

    We can't reconstruct the true per-message time (chat_history entries carry
    no timestamps), so updated_at — the last time the row was touched — is the
    best available proxy for sessions that already have messages. Ghost
    sessions (no messages) are left NULL so they sort to the bottom.
    """
    ChatSession = apps.get_model('chat', 'ChatSession')
    ChatSession.objects.filter(message_count__gt=0).update(
        last_message_at=models.F('updated_at')
    )


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0019_productlinkclick'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='last_message_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.RunPython(backfill_last_message_at, noop_reverse),
    ]
