# Generated by Django 4.2.29 on 2026-06-23 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0020_chatsession_last_message_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatsession',
            name='channel',
            field=models.CharField(choices=[('website', 'Website'), ('whatsapp', 'WhatsApp'), ('messenger', 'Messenger'), ('instagram', 'Instagram'), ('telegram', 'Telegram')], default='website', max_length=20),
        ),
        migrations.AlterField(
            model_name='chatsession',
            name='kanban_state',
            field=models.CharField(choices=[('NEW', 'New'), ('ENGAGED', 'Engaged'), ('QUALIFIED', 'Qualified'), ('HOT_LEAD', 'Hot Lead'), ('READY_TO_BUY', 'Ready to Buy'), ('CONVERTED', 'Converted'), ('LOST', 'Lost')], default='NEW', max_length=20),
        ),
    ]
