# Generated by Django 4.2.29 on 2026-06-23 05:13

import chat.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_tenantprofile_manual_plan_override'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0021_alter_chatsession_channel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_id', models.CharField(db_index=True, max_length=255)),
                ('file', models.FileField(upload_to=chat.models._attachment_upload_path)),
                ('kind', models.CharField(choices=[('image', 'Image'), ('file', 'File'), ('audio', 'Audio')], default='file', max_length=10)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('mime', models.CharField(blank=True, max_length=120)),
                ('size', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_attachments', to='users.client')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_attachments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
