# Generated by Django 4.2.29 on 2026-06-24 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0022_chatattachment'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='chatsession',
            index=models.Index(fields=['client', '-last_message_at'], name='cs_client_lastmsg_idx'),
        ),
        migrations.AddIndex(
            model_name='chatsession',
            index=models.Index(fields=['client', '-created_at'], name='cs_client_created_idx'),
        ),
        migrations.AddIndex(
            model_name='chatsession',
            index=models.Index(fields=['client', 'kanban_state'], name='cs_client_kanban_idx'),
        ),
        migrations.AddIndex(
            model_name='chatsession',
            index=models.Index(fields=['client', 'conversation_state'], name='cs_client_state_idx'),
        ),
    ]
