# Generated by Django 4.2.29 on 2026-06-25 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0023_chatsession_cs_client_lastmsg_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='greeting_intro_sent',
            field=models.BooleanField(default=False),
        ),
    ]
