# Generated by Django 4.2.29 on 2026-06-26 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0024_chatsession_greeting_intro_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='last_proactive_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='proactive_count',
            field=models.IntegerField(default=0),
        ),
    ]
