# Generated by Django 4.2.29 on 2026-03-13 08:34

from django.db import migrations, models
import pgvector.django.vector


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0002_documentchunk_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentchunk',
            name='embedding',
            field=pgvector.django.vector.VectorField(dimensions=1024),
        ),
        migrations.AlterField(
            model_name='documentchunk',
            name='product_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
