# Generated by Django 4.2.29 on 2026-05-22 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0004_add_webhookevent_model'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='webhookevent',
            new_name='scraper_web_client__42098e_idx',
            old_name='scraper_web_client__1ce4a8_idx',
        ),
    ]
