# Generated by Django 4.2.29 on 2026-06-24 03:17

from django.db import migrations, models
import pgvector.django.indexes


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0005_v2_architecture_stubs'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='documentchunk',
            index=pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['embedding'], m=16, name='docchunk_embedding_hnsw', opclasses=['vector_cosine_ops']),
        ),
        migrations.AddIndex(
            model_name='documentchunk',
            index=models.Index(fields=['client'], name='docchunk_client_idx'),
        ),
    ]
