# Generated by Django 4.2.29 on 2026-06-25 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0030_client_assistant_intro_client_auto_close_seconds_and_more'),
        ('scraper', '0006_documentchunk_docchunk_embedding_hnsw_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SitePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=1000)),
                ('url', models.URLField(max_length=1000)),
                ('title', models.CharField(blank=True, max_length=300)),
                ('page_type', models.CharField(default='fallback', max_length=32)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='site_pages', to='users.client')),
            ],
            options={
                'ordering': ['path'],
                'indexes': [models.Index(fields=['client', 'page_type'], name='scraper_sit_client__6a7198_idx')],
                'unique_together': {('client', 'path')},
            },
        ),
    ]
